version: "3.8"

services:

  cid-checker-frontend:
    hostname: cid-checker-frontend
    container_name: cid-checker-frontend
    image: cid-checker-frontend:1.0.0
    restart: always
    ports:
      - 80:80

  cid-checker-backend:
    hostname: cid-checker-backend
    container_name: cid-checker-backend
    image: cid-checker-backend:1.0.0
    restart: always
    environment:
      NODE_ENV: "production"
      PORT: "${PORT}"
      CID_DB_CONNECTIONSTRING: "${CID_DB_CONNECTIONSTRING}"
      CID_DB_NAME: "${CID_DB_NAME}"
      CID_DATABASE_USER: "${CID_DATABASE_USER}"
      CID_DATABASE_PASSWORD: "${CID_DATABASE_PASSWORD}"
      CID_LOTUS_RPCURL: "${CID_LOTUS_RPCURL}"
      CID_LOTUS_JWT_TOKEN: "${CID_LOTUS_JWT_TOKEN}"

#  cid-checker-watcher:
#    hostname: cid-checker-watcher
#    container_name: cid-checker-watcher
#    image: cid-checker-watcher:1.0.0
#    restart: always
#    environment:
#      NODE_ENV: "production"
#      SLEEP_TIPSET_CHECK_MS: "${SLEEP_TIPSET_CHECK_MS}"
#      DEBUG_FD: "${DEBUG_FD}"
#      CID_DB_CONNECTIONSTRING: "${CID_DB_CONNECTIONSTRING}"
#      CID_DB_NAME: "${CID_DB_NAME}"
#      CID_DATABASE_USER: "${CID_DATABASE_USER}"
#      CID_DATABASE_PASSWORD: "${CID_DATABASE_PASSWORD}"
#      CID_LOTUS_RPCURL: "${CID_LOTUS_RPCURL}"
#      CID_LOTUS_JWT_TOKEN: "${CID_LOTUS_JWT_TOKEN}"
#      DEALS_PAGE_SIZE: "${DEALS_PAGE_SIZE}"

  cid-checker-mongo:
      hostname: cid-checker-mongo
      container_name: cid-checker-mongo
      image: mongo:5.0.4
      restart: always
      volumes: 
        - mongo-data:/data/db
      ports:
        - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: "${CID_DATABASE_USER}"
        MONGO_INITDB_ROOT_PASSWORD: "${CID_DATABASE_PASSWORD}"
  
volumes:
  mongo-data:
    external: true
    name: mongo-data

